[package]
name = "scrotto"
version = "0.1.0"
edition = "2021"

[dependencies]
clipboard = "0.5"
notify-rust = "4"
screenshots = "0.3"
anyhow = "1"
ashpd = { version = "0.6", default-features = false, features = ["tokio"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }
    
